# Generated by Django 6.0.4 on 2026-05-02 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پارکینگ')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تعرفه')),
                ('vehicle_type', models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت'), ('truck', 'وانت/کامیون')], default='car', max_length=20, verbose_name='نوع وسیله نقلیه')),
                ('first_hour_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ساعت اول')),
                ('additional_hour_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه هر ساعت بعدی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تعرفه',
                'verbose_name_plural': 'تعرفه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='مثال: برای خودرو: 12ب345-67 ، برای موتور: 8 رقم', max_length=15, unique=True, verbose_name='شماره پلاک')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(blank=True, max_length=11, verbose_name='تلفن مالک')),
                ('type', models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت'), ('truck', 'وانت/کامیون')], default='car', max_length=20, verbose_name='نوع وسیله')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='کد محل')),
                ('level', models.CharField(max_length=255, verbose_name='طبقه')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='اشغال است؟')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkinglot', verbose_name='پارکینگ')),
            ],
            options={
                'verbose_name': 'جایگاه پارک',
                'verbose_name_plural': 'جایگاه\u200cهای پارک',
                'unique_together': {('parking_lot', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('total_duration_minutes', models.PositiveIntegerField(blank=True, help_text='بعد از خروج محاسبه و ذخیره می\u200cشود.', null=True, verbose_name='مدت کل (دقیقه)')),
                ('status', models.CharField(choices=[('open', 'باز (در حال پارک)'), ('closed', 'بسته (خارج شده)'), ('cancelled', 'لغو شده')], default='open', max_length=255, verbose_name='وضعیت')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parkingspot', verbose_name='جایگاه')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.vehicle', verbose_name='وسیله نقلیه')),
            ],
            options={
                'verbose_name': 'سشن پارک',
                'verbose_name_plural': 'سشن\u200cهای پارک',
            },
        ),
    ]
