# Generated by Django 6.0.4 on 2026-06-05 13:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پارکینگ / مشتری')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('admin', 'ادمین'), ('operator', 'اپراتور')], default='operator', max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='parking.customer', verbose_name='مشتری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر مشتری',
                'verbose_name_plural': 'کاربران مشتریان',
                'ordering': ['customer', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پارکینگ')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='parking.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پارکینگ',
                'verbose_name_plural': 'پارکینگ\u200cها',
                'ordering': ['customer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='کد محل')),
                ('level', models.CharField(max_length=255, verbose_name='طبقه')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='اشغال است؟')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkinglot', verbose_name='پارکینگ')),
            ],
            options={
                'verbose_name': 'جایگاه پارک',
                'verbose_name_plural': 'جایگاه\u200cهای پارک',
                'ordering': ['parking_lot', 'level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ورود')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('total_duration_minutes', models.PositiveIntegerField(blank=True, help_text='بعد از خروج محاسبه و ذخیره می\u200cشود.', null=True, verbose_name='مدت کل (دقیقه)')),
                ('status', models.CharField(choices=[('open', 'باز (در حال پارک)'), ('closed', 'بسته (خارج شده)'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, help_text='پس از ثبت خروج خودکار محاسبه می\u200cشود', max_digits=10, null=True, verbose_name='هزینه محاسبه\u200cشده')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parkingspot', verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'سشن پارک',
                'verbose_name_plural': 'سشن\u200cهای پارک',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('payment_method', models.CharField(blank=True, choices=[('pos', 'پرداخت با کارتخوان'), ('cash', 'پرداخت نقدی'), ('card_to_card_transfer', 'پرداخت با کارت به کارت'), ('online_gateway', 'پرداخت با درگاه آنلاین')], max_length=50, null=True, verbose_name='نحوه پرداخت')),
                ('payment_status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت پرداخت')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(verbose_name='شناسه اصلی پرداخت')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('payment_time', models.DateTimeField(verbose_name='زمان پرداخت')),
                ('payment_method', models.CharField(blank=True, choices=[('pos', 'پرداخت با کارتخوان'), ('cash', 'پرداخت نقدی'), ('card_to_card_transfer', 'پرداخت با کارت به کارت'), ('online_gateway', 'پرداخت با درگاه آنلاین')], max_length=50, null=True, verbose_name='نحوه پرداخت')),
                ('payment_status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], max_length=20, verbose_name='وضعیت پرداخت')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان حذف')),
                ('deleted_by', models.CharField(blank=True, help_text='نام کاربری فردی که پرداخت را حذف کرده است', max_length=150, null=True, verbose_name='حذف توسط')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.customer', verbose_name='مشتری')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'تاریخچه پرداخت',
                'verbose_name_plural': 'تاریخچه پرداخت\u200cها',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان صدور رسید')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='شماره رسید')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ روی رسید')),
                ('content', models.TextField(blank=True, help_text='متن آماده چاپ شامل زمان ورود و خروج، کد جایگاه، شماره پلاک، شماره رسید، روش پرداخت و هزینه', null=True, verbose_name='متن رسید')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='parking.payment', verbose_name='پرداخت')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'رسید',
                'verbose_name_plural': 'رسیدها',
                'ordering': ['-issue_time'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(verbose_name='شناسه اصلی رسید')),
                ('issue_time', models.DateTimeField(verbose_name='زمان صدور رسید')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='شماره رسید')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ روی رسید')),
                ('content', models.TextField(blank=True, null=True, verbose_name='متن رسید')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان حذف')),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='حذف توسط')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.customer', verbose_name='مشتری')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_histories', to='parking.payment', verbose_name='پرداخت')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_histories', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'تاریخچه رسید',
                'verbose_name_plural': 'تاریخچه رسیدها',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تعرفه')),
                ('vehicle_type', models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت'), ('truck', 'وانت/کامیون')], default='car', max_length=20, verbose_name='نوع وسیله نقلیه')),
                ('first_hour_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ساعت اول')),
                ('additional_hour_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه هر ساعت بعدی')),
                ('daily_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='هزینه توقف کامل ۲۴ ساعته', max_digits=10, verbose_name='هزینه شبانه\u200cروزی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='parking.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'تعرفه',
                'verbose_name_plural': 'تعرفه\u200cها',
                'ordering': ['customer', 'vehicle_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='مثال: برای خودرو: 12ب345-67 ، برای موتور: 8 رقم', max_length=15, verbose_name='شماره پلاک')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(blank=True, max_length=11, verbose_name='تلفن مالک')),
                ('type', models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت'), ('truck', 'وانت/کامیون')], default='car', max_length=20, verbose_name='نوع وسیله')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='رنگ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='parking.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'وسیله نقلیه',
                'verbose_name_plural': 'وسایل نقلیه',
                'ordering': ['customer', 'owner_name', 'plate_number'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(verbose_name='شناسه اصلی سشن')),
                ('entry_time', models.DateTimeField(verbose_name='زمان ورود')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('status', models.CharField(max_length=20, verbose_name='وضعیت')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه محاسبه\u200cشده')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان حذف')),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='حذف شده توسط')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.customer', verbose_name='مشتری')),
                ('parking_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkinglot', verbose_name='پارکینگ')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingspot', verbose_name='جای پارک')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.vehicle', verbose_name='وسیله نقلیه')),
            ],
            options={
                'verbose_name': 'تاریخچه سشن پارک',
                'verbose_name_plural': 'تاریخچه سشن\u200cهای پارک',
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.vehicle', verbose_name='وسیله نقلیه'),
        ),
        migrations.AddConstraint(
            model_name='parkinglot',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_parking_lot_name_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('parking_lot', 'code'), name='unique_spot_code_per_parking_lot'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'vehicle_type'), name='unique_active_tariff_per_customer_vehicle_type'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('customer', 'plate_number'), name='unique_vehicle_plate_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('vehicle',), name='unique_open_session_per_vehicle'),
        ),
    ]
