# Generated by Django 6.0.4 on 2026-06-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_phone',
        ),
    ]
