# Generated by Django 6.0.4 on 2026-05-02 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ورود'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('payment_method', models.CharField(choices=[('pos', 'پرداخت با کارتخوان'), ('cash', 'پرداخت نقدی'), ('card_to_card_transfer', 'پرداخت با کارت به کارت'), ('online_gateway', 'پرداخت با درگاه آنلاین')], max_length=50, verbose_name='نحوه پرداخت')),
                ('payment_status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت پرداخت')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان صدور رسید')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='شماره رسید')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ روی رسید')),
                ('content', models.TextField(blank=True, help_text='متن آماده چاپ شامل زمان ورود و خروج، کد جایگا،شماره پلاک،شماره رسید،روش پرداخت و هزینه', null=True, verbose_name='متن رسید')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='parking.payment', verbose_name='پرداخت')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'رسید',
                'verbose_name_plural': 'رسیدها',
            },
        ),
    ]
