# Generated by Django 6.0.4 on 2026-05-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingsession_entry_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'ordering': ['name'], 'verbose_name': 'پارکینگ', 'verbose_name_plural': 'پارکینگ ها '},
        ),
        migrations.AlterModelOptions(
            name='parkingsession',
            options={'ordering': ['-entry_time', 'vehicle'], 'verbose_name': 'سشن پارک', 'verbose_name_plural': 'سشن\u200cهای پارک'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['parking_lot', 'level', 'code'], 'verbose_name': 'جایگاه پارک', 'verbose_name_plural': 'جایگاه\u200cهای پارک'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_time'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issue_time'], 'verbose_name': 'رسید', 'verbose_name_plural': 'رسیدها'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['vehicle_type', 'name'], 'verbose_name': 'تعرفه', 'verbose_name_plural': 'تعرفه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['owner_name', 'plate_number'], 'verbose_name': 'ماشین', 'verbose_name_plural': 'ماشین ها'},
        ),
    ]
