# Generated by Django 6.0.4 on 2026-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_vehicle_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('owner', 'مالک'), ('operator', 'اپراتور')], default='operator', max_length=20, verbose_name='نقش'),
        ),
    ]
