# Generated by Django 6.0.4 on 2026-06-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_customeruser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
    ]
