# Generated by Django 6.0.4 on 2026-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='archived_entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود آرشیوی'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='archived_exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج آرشیوی'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='archived_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='روش پرداخت آرشیوی'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='archived_payment_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت پرداخت آرشیوی'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='archived_spot_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد جایگاه آرشیوی'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='archived_vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پلاک آرشیوی'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='content',
            field=models.TextField(blank=True, help_text='متن آماده چاپ شامل زمان ورود و خروج، کد جایگاه، شماره پلاک، شماره رسید، روش پرداخت و هزینه', null=True, verbose_name='متن رسید'),
        ),
    ]
