# Generated by Django 6.0.4 on 2026-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_payment_payment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='car_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='ظرفیت جایگاه خودرو'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='motorcycle_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='ظرفیت جایگاه موتور'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت'), ('truck', 'وانت/کامیون')], default='car', max_length=20, verbose_name='نوع جایگاه'),
        ),
    ]
