# Generated by Django 6.0.4 on 2026-05-09 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_receipt_archived_entry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='archived_entry_time',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='archived_exit_time',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='archived_payment_method',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='archived_payment_status',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='archived_spot_code',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='archived_vehicle_plate',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.parkingsession', verbose_name='سشن پارک'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='content',
            field=models.TextField(blank=True, help_text='متن آماده چاپ شامل زمان ورود و خروج، کد جایگا،شماره پلاک،شماره رسید،روش پرداخت و هزینه', null=True, verbose_name='متن رسید'),
        ),
        migrations.CreateModel(
            name='ParkingSessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(verbose_name='شناسه اصلی سشن')),
                ('entry_time', models.DateTimeField(verbose_name='زمان ورود')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('status', models.CharField(max_length=20, verbose_name='وضعیت')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه محاسبه\u200cشده')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان حذف')),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='حذف شده توسط')),
                ('parking_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkinglot', verbose_name='پارکینگ')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingspot', verbose_name='جای پارک')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.vehicle', verbose_name='وسیله نقلیه')),
            ],
            options={
                'verbose_name': 'تاریخچه سشن پارک',
                'verbose_name_plural': 'تاریخچه سشن\u200cهای پارک',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(verbose_name='شناسه اصلی پرداخت')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('payment_time', models.DateTimeField(verbose_name='زمان پرداخت')),
                ('payment_method', models.CharField(blank=True, choices=[('pos', 'پرداخت با کارتخوان'), ('cash', 'پرداخت نقدی'), ('card_to_card_transfer', 'پرداخت با کارت به کارت'), ('online_gateway', 'پرداخت با درگاه آنلاین')], max_length=50, null=True, verbose_name='نحوه پرداخت')),
                ('payment_status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], max_length=20, verbose_name='وضعیت پرداخت')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان حذف')),
                ('deleted_by', models.CharField(blank=True, help_text='نام کاربری فردی که پرداخت را حذف کرده است', max_length=150, null=True, verbose_name='حذف توسط')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'تاریخچه پرداخت',
                'verbose_name_plural': 'تاریخچه پرداخت\u200cها',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(verbose_name='شناسه اصلی رسید')),
                ('issue_time', models.DateTimeField(verbose_name='زمان صدور رسید')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='شماره رسید')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ روی رسید')),
                ('content', models.TextField(blank=True, null=True, verbose_name='متن رسید')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان حذف')),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='حذف توسط')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_histories', to='parking.payment', verbose_name='پرداخت')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_histories', to='parking.parkingsession', verbose_name='سشن پارک')),
            ],
            options={
                'verbose_name': 'تاریخچه رسید',
                'verbose_name_plural': 'تاریخچه رسیدها',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
