# Generated by Django 6.0.4 on 2026-06-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkinglot_car_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
    ]
