# Generated by Django 6.0.4 on 2026-06-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingspot_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate_number'], 'verbose_name': 'وسیله نقلیه', 'verbose_name_plural': 'وسایل نقلیه'},
        ),
        migrations.RemoveConstraint(
            model_name='parkingspot',
            name='unique_spot_code_per_parking_lot',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت')], default='car', max_length=20, verbose_name='نوع جایگاه'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت')], default='car', max_length=20, verbose_name='نوع وسیله'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('spot',), name='unique_open_session_per_spot'),
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parking_lot', 'code'), name='unique_active_spot_code_per_lot'),
        ),
    ]
