# Generated by Django 6.0.4 on 2026-05-11 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_remove_receipt_archived_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='هزینه توقف کامل ۲۴ ساعته', max_digits=10, verbose_name='هزینه شبانه\u200cروزی'),
        ),
    ]
