# Generated by Django 6.0.4 on 2026-06-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتورسیکلت')], default='car', max_length=20, verbose_name='نوع وسیله نقلیه'),
        ),
    ]
