# Generated by Django 6.0.4 on 2026-05-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_tariff_daily_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('vehicle',), name='unique_open_session_per_vehicle'),
        ),
    ]
