# Generated by Django 6.0.4 on 2026-06-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_remove_vehicle_owner_name_alter_tariff_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.parkingsession', verbose_name='سشن پارک'),
        ),
    ]
