# Generated by Django 6.0.4 on 2026-06-08 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='parking.parkinglot', verbose_name='پارکینگ مجاز'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='floor_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد طبقات'),
        ),
    ]
