# Generated by Django 6.0.4 on 2026-06-09 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_customeruser_parking_lot_parkinglot_floor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='car_capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='ظرفیت جایگاه خودرو'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='floor_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='motorcycle_capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='ظرفیت جایگاه موتور'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام پارکینگ'),
        ),
    ]
