# Generated by Django 6.0.4 on 2026-06-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_parkinglot_car_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='نام کاربری')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=120, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('reviewing', 'در حال بررسی'), ('resolved', 'حل شده'), ('rejected', 'رد شده')], default='reviewing', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='parking.customer', verbose_name='مشتری')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش مشکل',
                'verbose_name_plural': 'باگ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
