# Generated by Django 6.0.4 on 2026-06-09 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_alter_customer_name_alter_customer_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='این فیلد فقط می\u200cتواند شامل حروف فارسی باشد.', regex='^[آابپتثجچحخدذرزژسشصضطظعغفقکكگلمنوهیيىۀةئؤء\\s\u200c]+$')], verbose_name='نام پارکینگ / مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='این فیلد فقط می\u200cتواند شامل حروف فارسی باشد.', regex='^[آابپتثجچحخدذرزژسشصضطظعغفقکكگلمنوهیيىۀةئؤء\\s\u200c]+$')], verbose_name='نام مالک'),
        ),
    ]
