# Generated by Django 6.0.4 on 2026-06-10 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_alter_customer_name_alter_customer_owner_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان اطلاعیه')),
                ('description', models.TextField(verbose_name='متن توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان مشاهده')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='parking.announcement', verbose_name='اطلاعیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشاهده اطلاعیه',
                'verbose_name_plural': 'مشاهده\u200cهای اطلاعیه',
                'ordering': ['-seen_at'],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_view_per_user')],
            },
        ),
    ]
