# Generated by Django 6.0.4 on 2026-06-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_announcement_announcementview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingsession',
            options={'ordering': ['-entry_time'], 'verbose_name': 'خودروی فعال', 'verbose_name_plural': 'خودروهای فعال'},
        ),
        migrations.AlterModelOptions(
            name='parkingsessionhistory',
            options={'verbose_name': 'تاریخچه خودروی فعال', 'verbose_name_plural': 'تاریخچه خودروهای فعال'},
        ),
        migrations.AlterField(
            model_name='parkingsessionhistory',
            name='original_id',
            field=models.IntegerField(verbose_name='شناسه اصلی خودروی فعال'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.parkingsession', verbose_name='خودروی فعال'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='parking.parkingsession', verbose_name='خودروی فعال'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='parking.parkingsession', verbose_name='خودروی فعال'),
        ),
        migrations.AlterField(
            model_name='receipthistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_histories', to='parking.parkingsession', verbose_name='خودروی فعال'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text='خودرو: 12ب345-67، موتور: 8 رقم', max_length=15, verbose_name='شماره پلاک'),
        ),
    ]
