# Generated by Django 6.0.4 on 2026-06-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_alter_parkingsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text='خودرو: 12ب345-67، موتور: 8 رقم', max_length=25, verbose_name='شماره پلاک'),
        ),
    ]
