# Generated by Django 6.0.4 on 2026-06-16 20:05

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_tariffs_to_first_parking_lot(apps, schema_editor):
    ParkingLot = apps.get_model('parking', 'ParkingLot')
    Tariff = apps.get_model('parking', 'Tariff')

    for tariff in Tariff.objects.filter(parking_lot__isnull=True):
        parking_lot = (
            ParkingLot.objects
            .filter(customer_id=tariff.customer_id)
            .order_by('name', 'id')
            .first()
        )

        if parking_lot:
            tariff.parking_lot_id = parking_lot.id
            tariff.save(update_fields=['parking_lot'])


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['customer', 'parking_lot', 'vehicle_type', 'name'], 'verbose_name': 'تعرفه', 'verbose_name_plural': 'تعرفه\u200cها'},
        ),
        migrations.RemoveConstraint(
            model_name='tariff',
            name='unique_active_tariff_per_customer_vehicle_type',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس پارکینگ'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='parking.parkinglot', verbose_name='پارکینگ'),
        ),
        migrations.RunPython(
            assign_existing_tariffs_to_first_parking_lot,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parking_lot', 'vehicle_type'), name='unique_active_tariff_per_lot_vehicle_type'),
        ),
    ]
