# Generated by Django 6.0.4 on 2026-06-16 23:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='additional_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه هر ساعت بعدی (تومان)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='هزینه توقف کامل ۲۴ ساعته (تومان)', max_digits=10, verbose_name='هزینه شبانه\u200cروزی (تومان)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='first_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ساعت اول (تومان)'),
        ),
    ]
